support for multiple message keys
yandex-cloud/fluent-bit-plugin-yandex pull request #18
Opened 2023-08-05 06:45 UTC by kruftik

* add support for a set of space-separated message keys in configuration
*fix docker image for up-to-date fluent-bit versions (they changed the base debian image)

2023-08-23 13:32 UTC, Direnol requested changes

2023-08-23 13:32 UTC, Direnol commented on plugin/key.go
> -	message      string
it doesnt look like backward compatible, please, support a new key instead of replacing the existing key

2023-08-23 13:32 UTC, Direnol commented on plugin/key.go
> +		} else {
too nested :)
let's make it more fancy without if else, use `continue` instead of nested if else

2023-08-24 11:13 UTC, positiveviking commented
Sorry but this changes brings some confusing logic to incorrect place.
Log records transformation should be placed to fluentbit configuration but not in plugins.

2023-08-24 11:13 UTC, closed without merging