Feature: folder id auto detection
yandex-cloud/fluent-bit-plugin-yandex pull request #3
Opened 2022-01-24 08:39 UTC by smi-mi

2022-01-24 08:40 UTC, smi-mi commented on config.go
> +		FolderID string `json:"folder-id"`
не уверена какой формат у response body

2022-01-24 12:18 UTC, aizyurov commented on config.go
> +		FolderID string `json:"folder-id"`
просто string, так что folderId = string(body)

2022-01-24 12:26 UTC, aizyurov commented on config.go
> +		return nil, fmt.Errorf("could not make request: %s", err)
Need better error message here and below - "could not make request to autodetect folder ID", otherwise the user will be confused with fluent bit making a mysterious request.

2022-01-26 10:18 UTC, candiduslynx requested changes
see comments

2022-01-26 10:18 UTC, candiduslynx commented on config.go
> +	req, err := http.NewRequest("GET", urlFolderID, nil)
[http.MethodGet](https://pkg.go.dev/net/http#pkg-constants)

2022-01-26 10:18 UTC, candiduslynx commented on config.go
> +		return nil, fmt.Errorf("could not get instance metadata to autodetect folder ID: %s", err)
`err.Error()`

2022-01-26 10:18 UTC, candiduslynx commented on config.go
> +		return nil, fmt.Errorf("could not make request to autodetect folder ID: %s", err)
`err.Error()`

2022-01-26 10:18 UTC, candiduslynx commented on config.go
> +		return nil, fmt.Errorf("request to autodetect folder ID returned status other than OK: %s", resp.Status)
status is untyped int, use `%d`

2022-01-26 10:18 UTC, candiduslynx commented on config.go
> +		return nil, fmt.Errorf("response body returned by request to autodetect folder ID read failed: %s", err)
`err.Error()`

2022-01-26 11:15 UTC, Direnol commented
может использовать пакет `cloud.google.com/go/compute/metadata` для работы с метадатой ?
Тогда атрибуты можно получить примерно так: `metadata.Get("yandex/folder-id")`, или создать инстанс с другим endpoint

2022-01-26 12:39 UTC, smi-mi commented on config.go
> +		return nil, fmt.Errorf("request to autodetect folder ID returned status other than OK: %s", resp.Status)
Это не StatusCode а просто Status. `field Status string of Response type e.g. "200 OK"`

2022-01-26 12:56 UTC, smi-mi commented
> может использовать пакет `cloud.google.com/go/compute/metadata` для работы с метадатой ? Тогда атрибуты можно получить примерно так: `metadata.Get("yandex/folder-id")`, или создать инстанс с другим endpoint

@Direnol Саша говорит, это должно работать не только на сервисных виртуалках, но и на пользовательских. Не может ли упасть `metadata.Get` у пользователя?

2022-01-27 12:10 UTC, Direnol commented
> > может использовать пакет `cloud.google.com/go/compute/metadata` для работы с метадатой ? Тогда атрибуты можно получить примерно так: `metadata.Get("yandex/folder-id")`, или создать инстанс с другим endpoint
> 
> @Direnol Саша говорит, это должно работать не только на сервисных виртуалках, но и на пользовательских. Не может ли упасть `metadata.Get` у пользователя?

Будет работать и на тех и на тех. Этот пакет просто для удобной работы с метаданными. Единственное, что я бы сделал возможность конфигурировать адрес, по которому ходить в метаданные. По умолчанию: `http://169.254.169.254`

2022-01-28 09:49 UTC, candiduslynx requested changes

2022-01-28 09:49 UTC, candiduslynx commented on config.go
> +	if metadataUrlEnv := os.Getenv(keyMetadataUrlEnv); len(metadataUrlEnv) > 0 {
```go
metadataEndpoint := os.Getenv(keyMetadataUrlEnv)
if len(metadataUrlEnv) == 0 {
  metadataEndpoint = "http://" + ycsdk.InstanceMetadataAddr
}
urlFolderID = metadataEndpoint + urlSuffixFolderID
```

2022-02-01 13:08 UTC, candiduslynx approved these changes

2022-02-01 13:09 UTC, merged